version: '2'
services:
  db: 
    image: mysql:5.7.13
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
  redis:
    image: redis
  
  sidekiq:
    build: .
    volumes:
      - .:/app
    links:
      - db
      - redis
      - es
    environment:
      REDIS_URL_SIDEKIQ: ${REDIS_URL_SIDEKIQ}
    env_file: .env
    command: bundle exec sidekiq
  
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    environment:
      - discovery.type=single-node
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200

  app: 
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes: 
        - .:/app
    ports: 
        - ${SERVER_PORT}:3000
    depends_on:
        - db
        - redis
        - sidekiq
        - es

    links:
        - db
        - redis
        - sidekiq
        - es
    environment:
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      REDIS_URL_SIDEKIQ: ${REDIS_URL_SIDEKIQ}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
volumes:
  redis:
  db_data:
  es_data: